### ISSUE TITLE
Interop with stock/non-PQ openssh failing

### ISSUE THREAD

**Issue by vt-alt** [open-quantum-safe/openssh-portable#87] opened 2021-02-28 23:15 UTC
When logging in from OpenSSH_7.9p1 client to OQS-OpenSSH_7.9-2020-08_p1 server there is a connection error:
```
...
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ssh-ed25519
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
...
debug3: receive packet: type 60
debug1: Server accepts key: /home/vt/.ssh/id_ed25519 ED25519 ...
debug3: sign_and_send_pubkey: ED25519 ...
debug3: sign_and_send_pubkey: signing using ssh-ed25519
debug3: send packet: type 50
debug3: receive packet: type 52
debug1: Authentication succeeded (publickey).
Authenticated to 10.4.0.61 ([10.4.0.61]:22).
debug1: channel 0: new [client-session]
debug3: ssh_session2_open: channel_new: 0
debug2: channel 0: send open
debug3: send packet: type 90
debug1: Entering interactive session.
debug1: pledge: network
Bad packet length 496648.
debug3: send packet: type 1
ssh_dispatch_run_fatal: Connection to 10.4.0.61 port 22: Connection corrupted

```
When logging in from OQS-OpenSSH_7.9-2020-08_p1 client to the same server there is no error.

**Comment by baentsch** [comment] 2021-05-24 07:42
This is logical as some OQS algorithms are blowing the packet size limit of a "stock" `openssh`: See this: https://github.com/open-quantum-safe/openssh/blob/c600d653b6ce79c81f98d674e99c16d816008301/packet.c#L102-L105

**Comment by vt-alt** [comment] 2021-06-02 20:25
@baentsch Thanks for the answer! But isn't this is major incompatibility with common openssh (making it impossible to connect to/from oqs-openssh)? [I don't use some OQS algorithms in the connection example.]

Maybe this situation could be improved so that when OQS algorithms are used packet size is increased, but when they aren't packet size is normal? Otherwise only oqs-openssh <-> oqs-openssh connections are possible even for non-oqs algorithms.

**Comment by vt-alt** [comment] 2021-06-02 20:33
To add context — I was willing to create an **experimental** oqs-openssh package for ALT Linux, but if `openssh` cannot be replaced with `oqs-openssh` people cannot use it in practice as they will not be able to ssh to non OQS hosts anymore.

**Comment by dstebila** [comment] 2021-06-03 00:53
Unless I misunderstand, having a larger `PACKET_MAX_SIZE` should allow the an oqs-openssh client and server to send and receive larger packets than plain openssh, but they would only do so if a (large) PQ algorithm is being used. When an oqs-openssh client proposes a non-PQ suite to a plain openssh server, that packet would be just as small as it originally was, and the plain openssh server should have no problems handling it.  Or am I missing something?

**Comment by baentsch** [comment] 2021-06-03 04:16
> When an oqs-openssh client proposes a non-PQ suite to a plain openssh server, that packet would be just as small as it originally was, and the plain openssh server should have no problems handling it.

This is also my understanding. _However_ @vt-alt you have a point in that your example was not actively using PQ; thus, your example should have worked/connected. Now understanding the ultimate goal of your test (ensuring PQ/non-PQ ssh interop), let me re-open the issue with a different title.

**Comment by baentsch** [comment] 2021-06-06 17:47
@vt-alt I now finally found time to re-do what you tried and everything worked perfectly: stock client -> OQS-sshd and also OQS-ssh -> stock sshd(s). Admittedly, I tried only the [OQS-v8 branch](https://github.com/open-quantum-safe/openssh/tree/OQS-v8) which is (quickly becoming) our new main branch with ED25519.

Now, some questions: Are you absolutely certain that no PQ-signature algorithms got (inadvertently) sent (causing a buffer problem as per the above)? How did you start the `sshd`? I tried this: `sudo /opt/openssh/sbin/sshd -p 2222 -d -o AuthorizedKeysFile=/home/mib/ssh_server/authorized_keys -o HostKeyAlgorithms=ssh-ed25519 -o PubkeyAcceptedKeyTypes=ssh-ed25519 -h /home/mib/ssh_server/id_ed25519` and on client side: `ssh -p 2222 mib@localhost -i ~/ssh_client/id_ed25519 -o PasswordAuthentication=no`. My local user ID obviously is "mib". You can see the full server-side trace below.

Full server log as per the above:
```
debug1: sshd version OQS-OpenSSH_8.4-2020-08_, OpenSSL 1.1.1  11 Sep 2018
debug1: private host key #0: ssh-ed25519 SHA256:uHK++NxhbH9uRDDYEGyyD1LyhUHko9bIm5z4yeGrdRQ
debug1: rexec_argv[0]='/opt/openssh/sbin/sshd'
debug1: rexec_argv[1]='-p'
debug1: rexec_argv[2]='2222'
debug1: rexec_argv[3]='-d'
debug1: rexec_argv[4]='-o'
debug1: rexec_argv[5]='AuthorizedKeysFile=/home/mib/ssh_server/authorized_keys'
debug1: rexec_argv[6]='-o'
debug1: rexec_argv[7]='HostKeyAlgorithms=ssh-ed25519'
debug1: rexec_argv[8]='-o'
debug1: rexec_argv[9]='PubkeyAcceptedKeyTypes=ssh-ed25519'
debug1: rexec_argv[10]='-h'
debug1: rexec_argv[11]='/home/mib/ssh_server/id_ed25519'
debug1: Set /proc/self/oom_score_adj from 0 to -1000
debug1: Bind to port 2222 on 0.0.0.0.
Server listening on 0.0.0.0 port 2222.
debug1: Bind to port 2222 on ::.
Server listening on :: port 2222.
debug1: Server will not fork when running in debugging mode.
debug1: rexec start in 5 out 5 newsock 5 pipe -1 sock 8
debug1: sshd version OQS-OpenSSH_8.4-2020-08_, OpenSSL 1.1.1  11 Sep 2018
debug1: private host key #0: ssh-ed25519 SHA256:uHK++NxhbH9uRDDYEGyyD1LyhUHko9bIm5z4yeGrdRQ
debug1: inetd sockets after dupping: 5, 5
Connection from 127.0.0.1 port 41494 on 127.0.0.1 port 2222 rdomain ""
debug1: Local version string SSH-2.0-OQS-OpenSSH_8.4-2020-08_
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.6p1 Ubuntu-4ubuntu0.3
debug1: match: OpenSSH_7.6p1 Ubuntu-4ubuntu0.3 pat OpenSSH_7.0*,OpenSSH_7.1*,OpenSSH_7.2*,OpenSSH_7.3*,OpenSSH_7.4*,OpenSSH_7.5*,OpenSSH_7.6*,OpenSSH_7.7* compat 0x04000002
debug1: permanently_set_uid: 124/65534 [preauth]
debug1: list_hostkey_types: ssh-ed25519 [preauth]
debug1: SSH2_MSG_KEXINIT sent [preauth]
debug1: SSH2_MSG_KEXINIT received [preauth]
debug1: kex: algorithm: curve25519-sha256 [preauth]
debug1: kex: host key algorithm: ssh-ed25519 [preauth]
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none [preauth]
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none [preauth]
debug1: expecting SSH2_MSG_KEX_ECDH_INIT [preauth]
debug1: rekey out after 134217728 blocks [preauth]
debug1: SSH2_MSG_NEWKEYS sent [preauth]
debug1: Sending SSH2_MSG_EXT_INFO [preauth]
debug1: expecting SSH2_MSG_NEWKEYS [preauth]
debug1: SSH2_MSG_NEWKEYS received [preauth]
debug1: rekey in after 134217728 blocks [preauth]
debug1: KEX done [preauth]
debug1: userauth-request for user mib service ssh-connection method none [preauth]
debug1: attempt 0 failures 0 [preauth]
debug1: userauth-request for user mib service ssh-connection method publickey [preauth]
debug1: attempt 1 failures 0 [preauth]
userauth_pubkey: key type ssh-rsa not in PubkeyAcceptedKeyTypes [preauth]
debug1: userauth-request for user mib service ssh-connection method publickey [preauth]
debug1: attempt 2 failures 1 [preauth]
userauth_pubkey: key type ssh-rsa not in PubkeyAcceptedKeyTypes [preauth]
debug1: userauth-request for user mib service ssh-connection method publickey [preauth]
debug1: attempt 3 failures 2 [preauth]
userauth_pubkey: key type ssh-rsa not in PubkeyAcceptedKeyTypes [preauth]
debug1: userauth-request for user mib service ssh-connection method publickey [preauth]
debug1: attempt 4 failures 3 [preauth]
debug1: userauth_pubkey: test pkalg ssh-ed25519 pkblob ED25519 SHA256:ezp1Y/tkER9ROFM95Z37VOPkjn+sWI7OVp/x6sPxrWc [preauth]
debug1: temporarily_use_uid: 1000/1000 (e=0/0)
debug1: trying public key file /home/mib/ssh_server/authorized_keys
debug1: fd 6 clearing O_NONBLOCK
debug1: /home/mib/ssh_server/authorized_keys:3: matching key found: ED25519 SHA256:ezp1Y/tkER9ROFM95Z37VOPkjn+sWI7OVp/x6sPxrWc
debug1: /home/mib/ssh_server/authorized_keys:3: key options: agent-forwarding port-forwarding pty user-rc x11-forwarding
Accepted key ED25519 SHA256:ezp1Y/tkER9ROFM95Z37VOPkjn+sWI7OVp/x6sPxrWc found at /home/mib/ssh_server/authorized_keys:3
debug1: restore_uid: 0/0
Postponed publickey for mib from 127.0.0.1 port 41494 ssh2 [preauth]
debug1: userauth-request for user mib service ssh-connection method publickey [preauth]
debug1: attempt 5 failures 3 [preauth]
debug1: temporarily_use_uid: 1000/1000 (e=0/0)
debug1: trying public key file /home/mib/ssh_server/authorized_keys
debug1: fd 6 clearing O_NONBLOCK
debug1: /home/mib/ssh_server/authorized_keys:3: matching key found: ED25519 SHA256:ezp1Y/tkER9ROFM95Z37VOPkjn+sWI7OVp/x6sPxrWc
debug1: /home/mib/ssh_server/authorized_keys:3: key options: agent-forwarding port-forwarding pty user-rc x11-forwarding
Accepted key ED25519 SHA256:ezp1Y/tkER9ROFM95Z37VOPkjn+sWI7OVp/x6sPxrWc found at /home/mib/ssh_server/authorized_keys:3
debug1: restore_uid: 0/0
debug1: auth_activate_options: setting new authentication options
Accepted publickey for mib from 127.0.0.1 port 41494 ssh2: ED25519 SHA256:ezp1Y/tkER9ROFM95Z37VOPkjn+sWI7OVp/x6sPxrWc
debug1: monitor_child_preauth: mib has been authenticated by privileged process
debug1: auth_activate_options: setting new authentication options [preauth]
debug1: monitor_read_log: child log fd closed
User child is on pid 2856
debug1: permanently_set_uid: 1000/1000
debug1: rekey in after 134217728 blocks
debug1: rekey out after 134217728 blocks
debug1: ssh_packet_set_postauth: called
debug1: active: key options: agent-forwarding port-forwarding pty user-rc x11-forwarding
debug1: Entering interactive session for SSH2.
debug1: server_init_dispatch
debug1: server_input_channel_open: ctype session rchan 0 win 1048576 max 16384
debug1: input_session_request
debug1: channel 0: new [server-session]
debug1: session_new: session 0
debug1: session_open: channel 0
debug1: session_open: session 0: link with channel 0
debug1: server_input_channel_open: confirm session
debug1: server_input_channel_req: channel 0 request pty-req reply 1
debug1: session_by_channel: session 0 channel 0
debug1: session_input_channel_req: session 0 req pty-req
debug1: Allocating pty.
debug1: session_new: session 0
debug1: session_pty_req: session 0 alloc /dev/pts/7
debug1: server_input_channel_req: channel 0 request env reply 0
debug1: session_by_channel: session 0 channel 0
debug1: session_input_channel_req: session 0 req env
debug1: server_input_channel_req: channel 0 request shell reply 1
debug1: session_by_channel: session 0 channel 0
debug1: session_input_channel_req: session 0 req shell
Starting session: shell on pts/7 for mib from 127.0.0.1 port 41494 id 0
debug1: Setting controlling tty using TIOCSCTTY.

```

**Comment by vt-alt** [comment] 2021-06-06 19:31
Of course, `sshd` is started with OQS algorithms enabled. Do you suggest disabling them? If so there is still no interop with generic OpenSSH as users cannot run OQS OpenSSH server and connect to the host from generic OpenSSH client.
```
5.11.21-un-def-alt1:~# /usr/sbin/sshd -d
debug1: sshd version OQS-OpenSSH_7.9-2020-08_, OpenSSL 1.1.1i  8 Dec 2020
debug1: private host key #0: ssh-rsa SHA256:S55R4DEAM5CULhicHTme8ebOLe3apyaKN8Ga3gx6TDU
debug1: private host key #1: ecdsa-sha2-nistp256 SHA256:FBDGLniuuO/UfP1e1CMTPzoX30/C/Eo5wgCK9p9Y+h4
debug1: private host key #2: ssh-ed25519 SHA256:HJ9knt1F/aJGHPiYDjFfp9iXgybu1LdHBxZtkUArylA
debug1: private host key #3: ssh-oqsdefault SHA256:yDMvnks9e9NuQKwvzRzD90YEaH+BxqLFQE42IRHxm+c
debug1: private host key #4: ssh-dilithium2 SHA256:+VQiwT6H3G/+4WR3E3dfaX89oGMrA8p3mIpI++2cZRg
debug1: private host key #5: ssh-falcon512 SHA256:GPRxueFrCJRxlnlEFY8AtbIf7TwOoDD/7UBWNiM+6Qs
debug1: private host key #6: ssh-picnicl1full SHA256:waQvgIRfUIS4bx36a8YQnLPheyXu1dvaLtsFM31eN8s
debug1: private host key #7: ssh-picnic3l1 SHA256:PgmbeFmOhts8c+bN4xaB3PWM3NzRAjWmTXfU5SFktDc
debug1: private host key #8: ssh-rainbowiclassic SHA256:OnKxzrjOrs/8hxLbihFIzd5EsviM63bSghMorgWZk8I
debug1: private host key #9: ssh-sphincsharaka128frobust SHA256:kgOSqAPMW/J7xlTW5h0XIe8/ZPtIp4jGYHX8eHdSeXU
debug1: private host key #10: ssh-sphincssha256128frobust SHA256:80hJgMMWuPKLSCtxSIcSj6IMLvViStNjtZ5eL2KJwVc
debug1: private host key #11: ssh-sphincsshake256128frobust SHA256:ITmJpIFlcMJceBfFMwMaU47CfHRr9Li4D6R6GPTOFOs
debug1: private host key #12: ssh-rsa3072-oqsdefault SHA256:lctAJ+ItvupfYyI7khnJ/HoCF2T8CN+9AJVkFfqypMQ
debug1: private host key #13: ssh-p256-oqsdefault SHA256:TLtb8kha88Dk5h5F62ynAKlD29mMR8UrWNNMsdhFFEY
debug1: private host key #14: ssh-rsa3072-dilithium2 SHA256:eF51RFndgbcQd9l4lebcmbdMCfRh4/igxexYcEwcETk
debug1: private host key #15: ssh-p256-dilithium2 SHA256:4TwgN3/AnHg6vcipC7iST6IhLD/pZ9VTvC52XtsPV+k
debug1: private host key #16: ssh-rsa3072-falcon512 SHA256:aIbK0sO1UG3ajcgincTLxjrA1cLhMLR3WyBlgErowJQ
debug1: private host key #17: ssh-p256-falcon512 SHA256:JeDcebpxuLyLVukrQ1RNuN7OMMMKP3zSWP+5ib6iUwg
debug1: private host key #18: ssh-rsa3072-picnicl1full SHA256:7nfa7WZq2nVVYbEOQbFcuccjhs7fOUJS1gnTJDx0n/4
debug1: private host key #19: ssh-p256-picnicl1full SHA256:G67u5Ow91HR5fEGeEUmt8Puvcp6+mnPJ8WAt4QftI70
debug1: private host key #20: ssh-rsa3072-picnic3l1 SHA256:1n3e9zc8lvhh2no+KFaRQKIF8L/Wc5txT1hdfbXuQc0
debug1: private host key #21: ssh-p256-picnic3l1 SHA256:ofDTbey1lG81wGIrkw1+T9gYkH7ccchWco+IOJNr/K0
debug1: private host key #22: ssh-rsa3072-rainbowiclassic SHA256:Qt7pm/aZYhepJRWMCYbkR4lbWFXmKDyeL9LdAkxri2k
debug1: private host key #23: ssh-p256-rainbowiclassic SHA256:yp/gDsyX0DacMwsmVb+zGWB9XwfHbAPhR/2KmpKmLdU
debug1: private host key #24: ssh-rsa3072-sphincsharaka128frobust SHA256:zTYTuQpMZ70712eTaL+cw2uxTERx5tqLFZra4cFZPbk
debug1: private host key #25: ssh-p256-sphincsharaka128frobust SHA256:MxzHUJGHdb5k4CVMk9M3F6Xj9J+stIuwGm1QjQuBups
debug1: private host key #26: ssh-rsa3072-sphincssha256128frobust SHA256:IRWSfX0PK+xr+6WlqwbvLxctn6aO9SXGcMmM2qibifE
debug1: private host key #27: ssh-p256-sphincssha256128frobust SHA256:ZKbo07m4V1+bnA4vstZQz5pj8LFcJXGLmLABosImjOY
debug1: private host key #28: ssh-rsa3072-sphincsshake256128frobust SHA256:AiOQIcCAbBDIg21prG6PyDm/q7vzVjmeuMcAVB0sgTs
debug1: private host key #29: ssh-p256-sphincsshake256128frobust SHA256:Ul39sZbHdV6wJTnGEmvK0U4n+c3VDQpnAxjzW08WYAE
debug1: rexec_argv[0]='/usr/sbin/sshd'
debug1: rexec_argv[1]='-d'
debug1: Set /proc/self/oom_score_adj from 0 to -1000
debug1: Bind to port 22 on 0.0.0.0.
Server listening on 0.0.0.0 port 22.
debug1: Bind to port 22 on ::.
Server listening on :: port 22.

debug1: Server will not fork when running in debugging mode.
debug1: rexec start in 5 out 5 newsock 5 pipe -1 sock 8
debug1: inetd sockets after dupping: 3, 3
Connection from 10.4.128.5 port 42282 on 10.4.0.61 port 22
debug1: Client protocol version 2.0; client software version OpenSSH_7.9
debug1: match: OpenSSH_7.9 pat OpenSSH* compat 0x04000000
debug1: Local version string SSH-2.0-OQS-OpenSSH_7.9-2020-08_
debug1: permanently_set_uid: 498/490 [preauth]
debug1: list_hostkey_types: rsa-sha2-512,rsa-sha2-256,ssh-rsa,ecdsa-sha2-nistp256,ssh-ed25519 [preauth]
debug1: SSH2_MSG_KEXINIT sent [preauth]
debug1: SSH2_MSG_KEXINIT received [preauth]
debug1: kex: algorithm: curve25519-sha256 [preauth]
debug1: kex: host key algorithm: ssh-ed25519 [preauth]
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none [preauth]
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none [preauth]
debug1: expecting SSH2_MSG_KEX_ECDH_INIT [preauth]
debug1: rekey after 134217728 blocks [preauth]
debug1: SSH2_MSG_NEWKEYS sent [preauth]
debug1: expecting SSH2_MSG_NEWKEYS [preauth]
debug1: SSH2_MSG_NEWKEYS received [preauth]
debug1: rekey after 134217728 blocks [preauth]
debug1: KEX done [preauth]
debug1: userauth-request for user root service ssh-connection method none [preauth]
debug1: attempt 0 failures 0 [preauth]
debug1: userauth-request for user root service ssh-connection method publickey [preauth]
debug1: attempt 1 failures 0 [preauth]
debug1: userauth_pubkey: test pkalg ssh-ed25519 pkblob ED25519 SHA256:IaPR4qIYS7sUYutipr5Kicf2E618U4TOONgwjrcSR5w [preauth]
debug1: temporarily_use_uid: 0/0 (e=0/0)
debug1: trying public key file /root/.ssh/authorized_keys
debug1: fd 4 clearing O_NONBLOCK
debug1: /root/.ssh/authorized_keys:3: matching key found: ED25519 SHA256:IaPR4qIYS7sUYutipr5Kicf2E618U4TOONgwjrcSR5w
debug1: /root/.ssh/authorized_keys:3: key options: agent-forwarding port-forwarding pty user-rc x11-forwarding
Accepted key ED25519 SHA256:IaPR4qIYS7sUYutipr5Kicf2E618U4TOONgwjrcSR5w found at /root/.ssh/authorized_keys:3
debug1: restore_uid: 0/0
Postponed publickey for root from 10.4.128.5 port 42282 ssh2 [preauth]
debug1: userauth-request for user root service ssh-connection method publickey [preauth]
debug1: attempt 2 failures 0 [preauth]
debug1: temporarily_use_uid: 0/0 (e=0/0)
debug1: trying public key file /root/.ssh/authorized_keys
debug1: fd 4 clearing O_NONBLOCK
debug1: /root/.ssh/authorized_keys:3: matching key found: ED25519 SHA256:IaPR4qIYS7sUYutipr5Kicf2E618U4TOONgwjrcSR5w
debug1: /root/.ssh/authorized_keys:3: key options: agent-forwarding port-forwarding pty user-rc x11-forwarding
Accepted key ED25519 SHA256:IaPR4qIYS7sUYutipr5Kicf2E618U4TOONgwjrcSR5w found at /root/.ssh/authorized_keys:3
debug1: restore_uid: 0/0
debug1: auth_activate_options: setting new authentication options
Accepted publickey for root from 10.4.128.5 port 42282 ssh2: ED25519 SHA256:IaPR4qIYS7sUYutipr5Kicf2E618U4TOONgwjrcSR5w
debug1: monitor_child_preauth: root has been authenticated by privileged process
debug1: auth_activate_options: setting new authentication options [preauth]
debug1: monitor_read_log: child log fd closed
debug1: rekey after 134217728 blocks
debug1: rekey after 134217728 blocks
debug1: ssh_packet_set_postauth: called
debug1: active: key options: agent-forwarding port-forwarding pty user-rc x11-forwarding
ssh_packet_send_debug: Connection reset by peer
debug1: do_cleanup
debug1: audit_event: unhandled event 12
```
This is the log of faulty connection on the server side.

**Comment by vt-alt** [comment] 2021-06-06 19:40
For the completeness I just tested with `/usr/sbin/sshd -d -h /etc/openssh/ssh_host_ed25519_key` and this does not cause connection errors. So, problem only if OQS algorithms are enabled on the server side.

**Comment by vt-alt** [comment] 2021-06-06 20:10
> Admittedly, I tried only the [OQS-v8 branch](https://github.com/open-quantum-safe/openssh/tree/OQS-v8) which is (quickly becoming) our new main branch with ED25519.

[Btw, if it will support ED25519 as a hybrid algorithm with OQS algorithms that would be really nice, because of the popularity of ED25519.]

I think the choice should be given to the end-users — the server should run with OQS enabled, but client users should be able to choose to connect with OQS (if they enable it) or using generic algorithms and generic OpenSSH clients. That way generic OpenSSH server may be replaced with OQS OpenSSH transparently. If we only enable generic and hybrid algorithms on the server side the security should not decrease in comparison to generic OpenSSH.

Please correct me if I'm wrong.

**Comment by baentsch** [comment] 2021-06-07 05:57
> So, problem only if OQS algorithms are enabled on the server side.

Thanks for that confirmation -- that then might explain things: As soon as one of the "crazy big" algorithms is enabled, the larger --and incompatible-- buffer size might be triggered. I need to read up on the SSH protocol to understand if/when this occurs (maybe the server proposes them all to the client and in so doing the problem hits? Maybe @dstebila or @xvzcf you already know?). Might disabling/removing Sphincs and Rainbow host keys already suffice (?) to achieve your stated goal:

> client users should be able to choose to connect with OQS (if they enable it) or using generic algorithms and generic OpenSSH clients

to which I fully agree.

Now, after having built also the old (7.9) `OQS-openssh` locally I still fail to reproduce the error you are reporting, though: I still can connect OK (albeit very slowly) with a stock ssh to an OQS-sshd... So, could I ask you which exact platform you are using? Do you possibly have a docker image with which to reproduce things _exactly_? Or could you share all steps/the script that led to the behaviour reported? Thanks in advance.

**Comment by dstebila** [comment] 2021-06-07 15:29
> Thanks for that confirmation -- that then might explain things: As soon as one of the "crazy big" algorithms is enabled, the larger --and incompatible-- buffer size might be triggered. I need to read up on the SSH protocol to understand if/when this occurs (maybe the server proposes them all to the client and in so doing the problem hits? Maybe @dstebila or @xvzcf you already know?). Might disabling/removing Sphincs and Rainbow host keys already suffice (?) to achieve your stated goal

If memory serves, we only increased `PACKET_MAX_SIZE`, which is an OpenSSH buffer size, but not the size of any length fields in the protocol because the SSHv2 protocol itself had 32-bit length fields which are sufficient.  See the discussion in sections 3.3 and 4.2 of https://eprint.iacr.org/2019/858.  

Perhaps Michael's last sentence quoted above is on to something: if the OQS-OpenSSH installation is configured with Sphincs/Rainbow host keys, perhaps those are being sent even if the client doesn't ask for them, which would then be larger than the buffer size that the plain OpenSSH client can handle...

**Comment by vt-alt** [comment] 2021-06-07 22:38
Further experiments show that when I disable any one of the following keys `Bad packet length` error disappears and I can ssh successfully: `ssh_host_p256_rainbowiclassic_key`, `ssh_host_rsa3072_rainbowiclassic_key`.
Disabling `*sphincs*` keys does not affect the connection. So, "bad" keys are `rainbow`.

Also, my sshd build has disabled in `oqs-template/generate.yml` — RAINBOW_III_CLASSIC and RAINBOW_V_CLASSIC, because these keys are very slow to keygen (many minutes) making sshd start unacceptably long.

We build using rpmbuild system. There is my repo: http://git.altlinux.org/people/vt/packages/?p=openssh.git;a=shortlog;h=refs/heads/openquantumsafe
Perhaps like this, it could be reproduced manually:
```
5.11.21-un-def-alt1:~# docker run --rm -it alt:sisyphus bash
[root@bbf090845480 /]# apt-get update
[root@bbf090845480 /]# apt-get install -y rpm-build git libssl-devel liboqs-devel su \
         pam_userpass-devel zlib-devel libkrb5-devel libaudit-devel libedit-devel \
         libselinux-devel python3-module-jinja2 python3-module-yaml
[root@bbf090845480 ~]# useradd builder
[root@bbf090845480 ~]# su - builder
[builder@bbf090845480 ~]$ mkdir -p /home/builder/RPM/SOURCES/
[builder@bbf090845480 ~]$ git clone git://git.altlinux.org/people/vt/packages/openssh.git openquantumsafe-openssh-7.9p1.202008
[builder@bbf090845480 ~]$ tar cf /home/builder/RPM/SOURCES/openquantumsafe-openssh-7.9p1.202008.tar openquantumsafe-openssh-7.9p1.202008
[builder@bbf090845480 ~]$ rpmbuild -bc openquantumsafe-openssh-7.9p1.202008/openssh.spec
```
It will execute commands from `%prep` and `%build` sections of the `.spec` with sources untarred in `/home/builder/RPM/BUILD` and build artifacts in `/home/builder/RPM/BUILD/openquantumsafe-openssh-7.9p1.202008`.
```
[builder@bbf090845480 ~]$ cd /home/builder/RPM/BUILD
[builder@bbf090845480 BUILD]$ find -name sshd -perm -1 -ls
 21502742   3624 -rwxr-xr-x   1 builder  builder   3707632 Jun  7 22:28 ./openquantumsafe-openssh-7.9p1.202008/sshd
```

**Comment by baentsch** [comment] 2021-06-11 12:30
I'm no particular fan of Rainbow and wouldn't mind you drop it completely from your packaging... But then again, we (want to) try to support all QSC algs wherever possible... So I wonder: 
1) Are you OK with the status of things as-is? If so, shall we close this issue? 
OR 
2) Should we try to create a variant in which Rainbow could be supported by the client (only)? That way (`sshd` without Rainbow, `ssh` with) the package could operate without undue delay on the server side _and_ connect to both classic crypto servers as well as (even Rainbow-enabled) QSC servers.
Any preference?

**Comment by vt-alt** [comment] 2021-06-11 13:40
I'm OK and we can close the issue. I will disable Rainbow as it significantly reduce overall user experience of sshd (in compare to other algos), because of its slowness and big packet issue. But, of course, to support it on client-only would be better (if user wants to connect to a 3rd party sshd). I will enable it if this option is available. Thanks!

**Closed as completed** 2021-06-16 13:20 UTC
