### ISSUE TITLE
Script run.sh fails on Ubuntu16.04 with openssl version 1.0.2g

### ISSUE THREAD

**Issue by jaimesaez97** [open-quantum-safe/openssh-portable#31] opened 2019-07-01 11:21 UTC
On the execution of `$ sudo ./run.sh` there's an error:

`configure:16615: error: *** Can't find LibOQS library (see config.log for details) ***`

I am executing the script from an Ubuntu 16.04 with openssl-1.0.2g (1 Mar 2016) installed and these are the steps taken:

` $ sudo apt install autoconf automake gcc libtool libssl-dev make unzip xsltproc `
` $ cd openssh-portable/oqs_test `
` $ sudo bash run.sh `

I have tryed executing the scripts one by one but the same error occurs.

¿Any advice?
Thanks

**Comment by jaimesaez97** [comment] 2019-07-02 10:45
The error is found in an undefined reference to CMP_LT_OS in the liboqs.so library `/home/osm/QKD/openssh-portable/oqs_test/tmp/install/lib/liboqs.so: undefined reference to '_CMP_LT_OS'`.
This is the code: `configure:16615: error: *** Can't find LibOQS library (see config.log for details) ***`.

**Comment by dstebila** [comment] 2019-07-05 14:47
Hi Jaime, we ran into this problem in another context.  Can you try running `CIRCLECI=true ./run.sh` and letting me know the result?  

This would be a temporary solution. A more permanent solution involves improving how AVX2 and other instructions are detected/used in liboqs, which I'm working on but isn't done yet (https://github.com/open-quantum-safe/liboqs/pull/509).

**Comment by dstebila** [comment] 2019-07-09 01:15
https://github.com/open-quantum-safe/liboqs/pull/519 may be a more permanent solution to this issue; need to check here once it lands.

**Comment by dstebila** [comment] 2019-07-10 01:37
I think open-quantum-safe/liboqs#519 has fixed this problem, at least I can no longer reproduce.

**Comment by dstebila** [comment] 2019-07-10 01:37
Please try running again with a fresh checkout.

**Comment by xvzcf** [comment] 2019-08-19 21:15
Closing this as there have been no further updates since the fix has been merged.

**Closed as completed by xvzcf** 2019-08-19 21:15 UTC
Labels: bug
